/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package IMS.view;

import IMS.controller.IngredientController;
import IMS.controller.InventoryController;
import IMS.domain.IngredientCode;
import IMS.domain.Inventory;
import RM.domain.Unit;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Heinrich
 */
public class InventoryPendingAddUi extends javax.swing.JFrame {
     private ArrayList<IngredientCode> arrIngredientCode;
     ArrayList<Unit> arrUnit;
     private InventoryPendingUi inventoryPendingUi;
     private InventoryController inventoryController;
    /**
     * Creates new form InventoryPendingAddUi
     */
    

    InventoryPendingAddUi(InventoryPendingUi inventoryPendingUi, InventoryController inventoryController) {
        this.inventoryController = inventoryController;
        this.inventoryPendingUi = inventoryPendingUi;
        initComponents();
        loadIngredientCode();
        loadUnit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox();
        jTextFieldQuantity = new javax.swing.JTextField();
        jButtonPlaceOrder = new javax.swing.JButton();
        jTextFieldUnitPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxUnit = new javax.swing.JComboBox();

        jLabel1.setText("Ingredient Code");

        jLabel3.setText("Quantity");

        jButtonPlaceOrder.setText("Place Order");
        jButtonPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlaceOrderActionPerformed(evt);
            }
        });

        jLabel2.setText("Unit");

        jLabel5.setText("Unit Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonPlaceOrder))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldUnitPrice)
                                    .addComponent(jComboBoxUnit, 0, 200, Short.MAX_VALUE)
                                    .addComponent(jTextFieldQuantity)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPlaceOrder)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlaceOrderActionPerformed
        // TODO add your handling code here:
        double unitPrice = Double.valueOf(jTextFieldUnitPrice.getText());
        int quantity = Integer.valueOf(jTextFieldQuantity.getText());
        double totalPrice = quantity * unitPrice;
        
        Inventory inventory = new Inventory(0, "",arrIngredientCode.get(jComboBox.getSelectedIndex()).getCode(), quantity, unitPrice, null, arrUnit.get(jComboBoxUnit.getSelectedIndex()).getCodeUnit(), totalPrice, new java.sql.Date(new java.util.Date().getTime()));
       
        inventoryController.saveInventoryPending(inventory);
        inventoryPendingUi.initTable();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonPlaceOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPlaceOrder;
    private javax.swing.JComboBox jComboBox;
    private javax.swing.JComboBox jComboBoxUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldUnitPrice;
    // End of variables declaration//GEN-END:variables
    private void loadIngredientCode(){
        
        IngredientController icc = new IngredientController();
       
        arrIngredientCode = icc.loadIngredientCode();
        
        String[] list = new String[arrIngredientCode.size()];
        
        for(int i = 0; i < arrIngredientCode.size(); i++){
            list[i] = arrIngredientCode.get(i).getBrand() + " " + arrIngredientCode.get(i).getName();
        }
        
        ComboBoxModel model = new DefaultComboBoxModel(list);
        jComboBox.setModel(model);
    }

    private void loadUnit() {
        arrUnit = inventoryController.loadUnit();
        
        String[] list = new String[arrUnit.size()];
        
        for(int i = 0; i < arrUnit.size(); i++){
            list[i] = arrUnit.get(i).getName();
        }
        ComboBoxModel model = new DefaultComboBoxModel(list);
        jComboBoxUnit.setModel(model);
    }
}
