/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package OMS.view;

import OMS.controller.BoosterController;
import OMS.controller.TransactionController;
import OMS.domain.Booster;
import OMS.domain.BoosterList;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;

/**
 *
 * @author Heinrich
 */
public class BoosterUi extends javax.swing.JPanel {
    private HashMap map;
    private DefaultListModel listModel;
    private MainUi mainUI;
    
    private TransactionController transactionController;
    
    private BoosterList boosterList;
    
    /**
     * Creates new form BoosterUi
     */
    
    public BoosterUi(){
        
    }
    
    public BoosterUi(MainUi mainUI, TransactionController transactionController) {
    
        this.mainUI = mainUI;
        this.transactionController = transactionController;
        
        listModel = new DefaultListModel();
        
        BoosterController boosterController = new BoosterController();
        map = new HashMap();
        
        boosterList = new BoosterList();
        
        ArrayList<Booster> arrBooster;
        
        arrBooster = boosterController.loadBooster();
        
        for(int i = 0; i < arrBooster.size(); i++){
            map.put(arrBooster.get(i).getName(), arrBooster.get(i));
            listModel.addElement(arrBooster.get(i).getName());
        }
       initComponents();
        
        //jList1.setModel(listModel);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListLeft = new javax.swing.JList();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListRight = new javax.swing.JList();
        jButtonContinue = new javax.swing.JButton();

        jListLeft.setModel(listModel//new javax.swing.AbstractListModel() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            //public int getSize() { return strings.length; }
            //public Object getElementAt(int i) { return strings[i]; }
        );
        jScrollPane1.setViewportView(jListLeft);

        jButtonAdd.setText(">>");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDelete.setText("<<");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jListRight.setModel(new DefaultListModel()//new javax.swing.AbstractListModel() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            //public int getSize() { return strings.length; }
            //public Object getElementAt(int i) { return strings[i]; }
        );
        jScrollPane2.setViewportView(jListRight);

        jButtonContinue.setText("Continue");
        jButtonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonContinue)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDelete))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jButtonContinue))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        //System.out.println(jListLeft.getSelectedValue());
        
        jListLeft.getSelectedValue();
        DefaultListModel model = (DefaultListModel) jListRight.getModel();
        model.addElement(jListLeft.getSelectedValue());
        jListRight.setModel(model);
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        
        int i = jListRight.getSelectedIndex();
        DefaultListModel model = (DefaultListModel) jListRight.getModel();
        model.removeElementAt(i);
        jListRight.setModel(model);
        jListRight.setSelectedIndex(i);
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinueActionPerformed
        // TODO add your handling code here:
        Booster[] booster;
        
        
        DefaultListModel model = (DefaultListModel) jListRight.getModel();
        int n = model.getSize();
        boosterList.createList(n);
        System.out.println(n);
        booster = boosterList.getList();
        for(int i = 0; i < n; i++){
            
            booster[i] = (Booster) map.get(model.get(i));
        }
        
        boosterList.setList(booster);
        
        transactionController.setBoosterList(boosterList);
        
        mainUI.moveToCash();
        
        
        
        
    }//GEN-LAST:event_jButtonContinueActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JList jListLeft;
    private javax.swing.JList jListRight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
