/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package OMS.view;

import OMS.controller.TransactionController;
import java.awt.event.KeyEvent;

/**
 *
 * @author Heinrich
 */
public class CashUi extends javax.swing.JPanel {
    private MainUi mainUi;
    private TransactionController transactionController;
    /**
     * Creates new form ChangeUi
     */
    public CashUi(MainUi mainUi, TransactionController transactionController) {
        initComponents();
        this.mainUi = mainUi;
        this.transactionController = transactionController;
        
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonClear = new javax.swing.JButton();
        jTextFieldRecievedAmt = new javax.swing.JTextField();
        jTextFieldChange = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButtonPeriod = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        jLabel1.setText("Amount Recieved");

        jLabel2.setText("Change");

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jTextFieldRecievedAmt.setEditable(false);
        jTextFieldRecievedAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRecievedAmtKeyPressed(evt);
            }
        });

        jTextFieldChange.setEditable(false);
        jTextFieldChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChangeActionPerformed(evt);
            }
        });

        jButton1.setText("1");

        jButton2.setText("2");

        jButton3.setText("3");

        jButton4.setText("4");

        jButton5.setText("5");

        jButton6.setText("6");

        jButton7.setText("7");

        jButton8.setText("8");

        jButton9.setText("8");

        jButton10.setText("0");

        jButtonPeriod.setText(".");

        jButton11.setText(";");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldChange, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRecievedAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton6))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton7)
                                .addComponent(jButtonPeriod))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton9))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldRecievedAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton8)
                            .addComponent(jButton9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton10)
                            .addComponent(jButtonPeriod)
                            .addComponent(jButton11))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRecievedAmtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRecievedAmtKeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyCode()){
            case KeyEvent.VK_0: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + 0);
                break;
            case KeyEvent.VK_1: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "1");
                break;
            case KeyEvent.VK_2: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "2");
                break;
            case KeyEvent.VK_3: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "3");
                break;
            case KeyEvent.VK_4: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "4");
                break;
            case KeyEvent.VK_5: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "5");
                break;
            case KeyEvent.VK_6: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "6");
                break;
            case KeyEvent.VK_7: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "7");
                break;
            case KeyEvent.VK_8: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "8");
                break;
            case KeyEvent.VK_9: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "9");
                break;
            case KeyEvent.VK_BACK_SPACE:{
                String temp = jTextFieldRecievedAmt.getText();
                jTextFieldRecievedAmt.setText(temp.substring(0, temp.length()-1));
                break;
            }
            case KeyEvent.VK_PERIOD: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + ".");
                break;
            case KeyEvent.VK_ENTER: calculate();
                
        }
       
    }//GEN-LAST:event_jTextFieldRecievedAmtKeyPressed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jTextFieldChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldChangeActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonPeriod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldChange;
    private javax.swing.JTextField jTextFieldRecievedAmt;
    // End of variables declaration//GEN-END:variables

    private void calculate() {
        double recievedAmt = Double.valueOf(jTextFieldRecievedAmt.getText());
        jTextFieldChange.setText(String.valueOf(transactionController.calculateChange(recievedAmt, mainUi.getTotalAmt())));
       
        
    }
    
    public void reset(){
        jTextFieldChange.setText("");
        jTextFieldRecievedAmt.setText("");
    }

    
}
