/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package OMS.view;

import OMS.controller.CashController;
import OMS.controller.TransactionController;
import OMS.domain.Cash;
import OMS.service.CashService;
import java.awt.event.KeyEvent;

/**
 *
 * @author Heinrich
 */
public class CashUi extends javax.swing.JPanel {
    private CashController cashController;
    private MainUi mainUi;
    private TransactionController transactionController;
    /**
     * Creates new form ChangeUi
     */
    public CashUi(MainUi mainUi, TransactionController transactionController) {
        initComponents();
        this.mainUi = mainUi;
        this.transactionController = transactionController;
        
        cashController = new CashController();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFinish = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonClear = new javax.swing.JButton();
        jTextFieldRecievedAmt = new javax.swing.JTextField();
        jTextFieldChange = new javax.swing.JTextField();

        jButtonFinish.setText("Finish");
        jButtonFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinishActionPerformed(evt);
            }
        });

        jLabel1.setText("Amount Recieved");

        jLabel2.setText("Change");

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jTextFieldRecievedAmt.setEditable(false);
        jTextFieldRecievedAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRecievedAmtKeyPressed(evt);
            }
        });

        jTextFieldChange.setEditable(false);
        jTextFieldChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonFinish))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldChange, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jTextFieldRecievedAmt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClear)
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldRecievedAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButtonFinish)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinishActionPerformed
        // TODO add your handling code here:
        transactionController.setCash(cashController.getCash());
    }//GEN-LAST:event_jButtonFinishActionPerformed

    private void jTextFieldRecievedAmtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRecievedAmtKeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyCode()){
            case KeyEvent.VK_0: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + 0);
                break;
            case KeyEvent.VK_1: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "1");
                break;
            case KeyEvent.VK_2: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "2");
                break;
            case KeyEvent.VK_3: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "3");
                break;
            case KeyEvent.VK_4: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "4");
                break;
            case KeyEvent.VK_5: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "5");
                break;
            case KeyEvent.VK_6: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "6");
                break;
            case KeyEvent.VK_7: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "7");
                break;
            case KeyEvent.VK_8: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "8");
                break;
            case KeyEvent.VK_9: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + "9");
                break;
            case KeyEvent.VK_BACK_SPACE:{
                String temp = jTextFieldRecievedAmt.getText();
                jTextFieldRecievedAmt.setText(temp.substring(0, temp.length()-1));
                break;
            }
            case KeyEvent.VK_PERIOD: jTextFieldRecievedAmt.setText(jTextFieldRecievedAmt.getText() + ".");
                break;
            case KeyEvent.VK_ENTER: calculate();
                
        }
       
    }//GEN-LAST:event_jTextFieldRecievedAmtKeyPressed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jTextFieldChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldChangeActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonFinish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldChange;
    private javax.swing.JTextField jTextFieldRecievedAmt;
    // End of variables declaration//GEN-END:variables

    private void calculate() {
        double recievedAmt = Double.valueOf(jTextFieldRecievedAmt.getText());
        cashController.setRecievedAmt(recievedAmt);
        //cashController.setPrice(transactionController.getMenuItem().getPrice());
        jTextFieldChange.setText(String.valueOf(cashController.calculateChange()));
        
    }

    
}
