/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package OMS.view;

import OMS.controller.ButtonListener;
import OMS.controller.MenuController;
import OMS.controller.TransactionController;
import OMS.domain.MenuItem;
import java.util.ArrayList;

/**
 *
 * @author Heinrich
 */
public class MenuUi extends javax.swing.JPanel {

    /**
     * Creates new form OrderUi
     */
    
    private MainUi mainUI;
    private TransactionController transactionController;
    
    public MenuUi(MainUi mainUI, TransactionController transactionController) {
    
        this.mainUI = mainUI;
        this.transactionController = transactionController;
        
        initComponents();
        MenuController menuController = new MenuController();
        
        try{
            addListener(menuController.loadRecipe());
        }catch(IndexOutOfBoundsException e){
            
        }
    }

            
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuButton1 = new javax.swing.JButton();
        menuButton2 = new javax.swing.JButton();
        menuButton3 = new javax.swing.JButton();
        menuButton4 = new javax.swing.JButton();
        menuButton5 = new javax.swing.JButton();
        menuButton6 = new javax.swing.JButton();
        menuButton7 = new javax.swing.JButton();
        menuButton8 = new javax.swing.JButton();
        menuButton9 = new javax.swing.JButton();
        menuButton10 = new javax.swing.JButton();
        menuButton11 = new javax.swing.JButton();
        menuButton12 = new javax.swing.JButton();
        menuButton13 = new javax.swing.JButton();
        menuButton14 = new javax.swing.JButton();
        menuButton15 = new javax.swing.JButton();
        menuButton16 = new javax.swing.JButton();
        menuButton17 = new javax.swing.JButton();
        menuButton18 = new javax.swing.JButton();
        menuButton19 = new javax.swing.JButton();
        menuButton20 = new javax.swing.JButton();
        menuButton21 = new javax.swing.JButton();
        menuButton22 = new javax.swing.JButton();
        menuButton23 = new javax.swing.JButton();
        menuButton24 = new javax.swing.JButton();

        menuButton1.setText("Menu 1");
        menuButton1.setMaximumSize(new java.awt.Dimension(70, 50));
        menuButton1.setMinimumSize(new java.awt.Dimension(70, 50));
        menuButton1.setPreferredSize(new java.awt.Dimension(110, 70));

        menuButton2.setText("Menu 2");
        menuButton2.setPreferredSize(new java.awt.Dimension(110, 70));

        menuButton3.setText("Menu 3");
        menuButton3.setPreferredSize(new java.awt.Dimension(110, 70));

        menuButton4.setText("Menu 4");
        menuButton4.setPreferredSize(new java.awt.Dimension(110, 70));

        menuButton5.setText("Menu 5");
        menuButton5.setPreferredSize(new java.awt.Dimension(110, 70));

        menuButton6.setText("Menu 6");
        menuButton6.setPreferredSize(new java.awt.Dimension(110, 70));

        menuButton7.setText("Menu 7");
        menuButton7.setPreferredSize(new java.awt.Dimension(110, 70));

        menuButton8.setText("Menu 8");

        menuButton9.setText("Menu 9");

        menuButton10.setText("Menu 10");

        menuButton11.setText("Menu 11");

        menuButton12.setText("Menu 12");

        menuButton13.setText("Menu 13");

        menuButton14.setText("Menu 14");

        menuButton15.setText("Menu 15");

        menuButton16.setText("Menu 16");

        menuButton17.setText("Menu 17");

        menuButton18.setText("Menu 18");

        menuButton19.setText("Menu 19");

        menuButton20.setText("Menu 20");

        menuButton21.setText("Menu 21");

        menuButton22.setText("Menu 22");

        menuButton23.setText("Menu 23");

        menuButton24.setText("Menu 24");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menuButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menuButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(menuButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menuButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(menuButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menuButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menuButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menuButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menuButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menuButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menuButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menuButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menuButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menuButton24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(menuButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(menuButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuButton16, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(menuButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuButton17, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(menuButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuButton21, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(menuButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuButton24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton menuButton1;
    private javax.swing.JButton menuButton10;
    private javax.swing.JButton menuButton11;
    private javax.swing.JButton menuButton12;
    private javax.swing.JButton menuButton13;
    private javax.swing.JButton menuButton14;
    private javax.swing.JButton menuButton15;
    private javax.swing.JButton menuButton16;
    private javax.swing.JButton menuButton17;
    private javax.swing.JButton menuButton18;
    private javax.swing.JButton menuButton19;
    private javax.swing.JButton menuButton2;
    private javax.swing.JButton menuButton20;
    private javax.swing.JButton menuButton21;
    private javax.swing.JButton menuButton22;
    private javax.swing.JButton menuButton23;
    private javax.swing.JButton menuButton24;
    private javax.swing.JButton menuButton3;
    private javax.swing.JButton menuButton4;
    private javax.swing.JButton menuButton5;
    private javax.swing.JButton menuButton6;
    private javax.swing.JButton menuButton7;
    private javax.swing.JButton menuButton8;
    private javax.swing.JButton menuButton9;
    // End of variables declaration//GEN-END:variables
   
    private void addListener(ArrayList<MenuItem> arrRecipe) throws IndexOutOfBoundsException{
        menuButton1.addActionListener(new ButtonListener(arrRecipe.get(0)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton1.setText(arrRecipe.get(0).getName());
        
        menuButton2.addActionListener(new ButtonListener(arrRecipe.get(1)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton2.setText(arrRecipe.get(1).getName());
        
        menuButton3.addActionListener(new ButtonListener(arrRecipe.get(2)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton3.setText(arrRecipe.get(2).getName());
        
        menuButton4.addActionListener(new ButtonListener(arrRecipe.get(3)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton4.setText(arrRecipe.get(3).getName());
        
        menuButton5.addActionListener(new ButtonListener(arrRecipe.get(4)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton5.setText(arrRecipe.get(4).getName());
        
        menuButton6.addActionListener(new ButtonListener(arrRecipe.get(5)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton6.setText(arrRecipe.get(5).getName());
        
        menuButton7.addActionListener(new ButtonListener(arrRecipe.get(6)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton7.setText(arrRecipe.get(6).getName());
        
        menuButton8.addActionListener(new ButtonListener(arrRecipe.get(7)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton8.setText(arrRecipe.get(7).getName());
        
        menuButton9.addActionListener(new ButtonListener(arrRecipe.get(8)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton9.setText(arrRecipe.get(8).getName());
        
        menuButton10.addActionListener(new ButtonListener(arrRecipe.get(9)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton10.setText(arrRecipe.get(9).getName());
        
        menuButton11.addActionListener(new ButtonListener(arrRecipe.get(10)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton11.setText(arrRecipe.get(10).getName());
        
        menuButton12.addActionListener(new ButtonListener(arrRecipe.get(11)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton12.setText(arrRecipe.get(11).getName());
        
        menuButton13.addActionListener(new ButtonListener(arrRecipe.get(12)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton13.setText(arrRecipe.get(12).getName());
        
        menuButton14.addActionListener(new ButtonListener(arrRecipe.get(13)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton14.setText(arrRecipe.get(13).getName());
        
        menuButton15.addActionListener(new ButtonListener(arrRecipe.get(14)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton15.setText(arrRecipe.get(14).getName());
        
        menuButton16.addActionListener(new ButtonListener(arrRecipe.get(15)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        
        menuButton16.setText(arrRecipe.get(15).getName());
        
        menuButton17.addActionListener(new ButtonListener(arrRecipe.get(16)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton17.setText(arrRecipe.get(16).getName());
        
        menuButton18.addActionListener(new ButtonListener(arrRecipe.get(17)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton18.setText(arrRecipe.get(17).getName());
        
        menuButton19.addActionListener(new ButtonListener(arrRecipe.get(18)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton19.setText(arrRecipe.get(18).getName());
        
        menuButton20.addActionListener(new ButtonListener(arrRecipe.get(19)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton20.setText(arrRecipe.get(19).getName());
        
        menuButton21.addActionListener(new ButtonListener(arrRecipe.get(20)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton21.setText(arrRecipe.get(20).getName());
        
        menuButton22.addActionListener(new ButtonListener(arrRecipe.get(21)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton22.setText(arrRecipe.get(21).getName());
        
        menuButton23.addActionListener(new ButtonListener(arrRecipe.get(22)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton23.setText(arrRecipe.get(2).getName());
        
        menuButton24.addActionListener(new ButtonListener(arrRecipe.get(23)) {
           @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(getRecipe());
            }
        });
        menuButton24.setText(arrRecipe.get(23).getName());
    }
  
    private void menuButton1ActionPerformed(MenuItem menuItem) {
        transactionController.addMenuItem(menuItem);
        mainUI.refreshTable();
    }
    
}
